server:
   port: 0
spring:
   application:
      name: crindex
   datasource:
      url: jdbc:sqlite:/d:/sqlite/crbook.db
      driver-class-name: org.sqlite.JDBC
#      url: jdbc:mysql://127.0.0.1/c71-s3-ply-blog
#      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: a
   jpa:
      show-sql: true
      properties:
         hibernate:
            format-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

logging:
   level:
#      root: debug
      com:
         yc:
            demo: debug